### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by Tobias-De** [v4lk/lwbd#4]
Hi, I try to use this Library in my Android Application. However i have been unsuccessfull so far.
Do i have to include any other Library besides your code from the Android branch?

My Code how I use this Library is:
```
File audioFile = new File("/storage/emulated/0/Music/song.mp3");
Beat[] beats = BeatDetector.detectBeats(temp, BeatDetector.AudioType.MP3);
```

The Error i get is the following:
`E/AndroidRuntime: FATAL EXCEPTION: Thread-11756
    Process: player.musik.test.de.musikplayer, PID: 20366
    java.lang.ExceptionInInitializerError
        at v4lk.lwbd.decoders.processing.jlayer.SynthesisFilter.load_d(SynthesisFilter.java:1626)
        at v4lk.lwbd.decoders.processing.jlayer.SynthesisFilter.<init>(SynthesisFilter.java:75)
        at v4lk.lwbd.decoders.processing.jlayer.Decoder.initialize(Decoder.java:283)
        at v4lk.lwbd.decoders.processing.jlayer.Decoder.decodeFrame(Decoder.java:138)
        at v4lk.lwbd.decoders.JLayerMp3Decoder.fillBuffer(JLayerMp3Decoder.java:69)
        at v4lk.lwbd.decoders.JLayerMp3Decoder.nextMonoFrame(JLayerMp3Decoder.java:44)
        at v4lk.lwbd.BeatDetector$AudioFunctions.calculateSpectralFluxes(BeatDetector.java:41)
        at v4lk.lwbd.BeatDetector.detectBeats(BeatDetector.java:202)
        at v4lk.lwbd.BeatDetector.detectBeats(BeatDetector.java:293)
        at v4lk.lwbd.BeatDetector.detectBeats(BeatDetector.java:262)
        at player.musik.test.de.musikplayer.MainActivity.loadMetaDataForSong(MainActivity.java:287)
        at player.musik.test.de.musikplayer.MainActivity.access$400(MainActivity.java:53)
        at player.musik.test.de.musikplayer.MainActivity$2.IterateFolder(MainActivity.java:380)
        at player.musik.test.de.musikplayer.MainActivity$2.run(MainActivity.java:364)
     Caused by: java.io.IOException: unable to load resource 'sfd.ser'
        at v4lk.lwbd.decoders.processing.jlayer.JavaLayerUtils.deserializeArrayResource(JavaLayerUtils.java:140)
        at v4lk.lwbd.decoders.processing.jlayer.SynthesisFilter.load_d(SynthesisFilter.java:1621)
        at v4lk.lwbd.decoders.processing.jlayer.SynthesisFilter.<init>(SynthesisFilter.java:75) 
        at v4lk.lwbd.decoders.processing.jlayer.Decoder.initialize(Decoder.java:283) 
        at v4lk.lwbd.decoders.processing.jlayer.Decoder.decodeFrame(Decoder.java:138) 
        at v4lk.lwbd.decoders.JLayerMp3Decoder.fillBuffer(JLayerMp3Decoder.java:69) 
        at v4lk.lwbd.decoders.JLayerMp3Decoder.nextMonoFrame(JLayerMp3Decoder.java:44) 
        at v4lk.lwbd.BeatDetector$AudioFunctions.calculateSpectralFluxes(BeatDetector.java:41) 
        at v4lk.lwbd.BeatDetector.detectBeats(BeatDetector.java:202) 
        at v4lk.lwbd.BeatDetector.detectBeats(BeatDetector.java:293) 
        at v4lk.lwbd.BeatDetector.detectBeats(BeatDetector.java:262) 
        at player.musik.test.de.musikplayer.MainActivity.loadMetaDataForSong(MainActivity.java:287) 
        at player.musik.test.de.musikplayer.MainActivity.access$400(MainActivity.java:53) 
        at player.musik.test.de.musikplayer.MainActivity$2.IterateFolder(MainActivity.java:380) 
        at player.musik.test.de.musikplayer.MainActivity$2.run(MainActivity.java:364) `

I know that it is not maintained anymore, I read the other Issues that are closed.
Why is this error happening and how can i fix it?
Any Help is greatly appreciated! Thanks 👍

**Comment by Tobias-De** [comment]
I fixed the Issue by creating an android ressource folder, putting the sfd.ser file there and load it in the mentioned function with  `str = context.getResources().openRawResource(R.raw.sfd);`

But now i am facing another Problem. 

The Call ` LinkedList<Float> spectralFluxes = AudioFunctions.calculateSpectralFluxes(decoder);` in BeatDetector never finishes. My Phone has a decently fast Processor (Snapdragon 820 with 4x 2,1 ghz) and the 2 minute long song was not finished after 45 minutes. what is going on with this library?

**Comment by qlyoung** [comment]
@Tobias-De Frankly I have not looked at or updated this library in 4+ years so I am not sure what could be causing it off the top of my head. Looking at the function in question it might be possible that `decoder.nextMonoFrame` is getting stuck and never returns a null frame to break the loop. I would set a breakpoint in that loop and inspect the contents of `protoframe` after a few minutes to see if it's still changing. Load times were always quite long with this library (it was one of my first programming projects and these days could definitely be done better with the NDK / recent Android functionality for realtime audio) but never approached anything like 45 minutes for me.

**Comment by Tobias-De** [comment]
photoframe keeps changing forever. 
I am honest. i dont know what a "flux" is, but would this library give me sort of "acurate" results if i would limit the size of "fluxes" to lets say 1000? Or does the Library need all the flux there is of a file?
If i would limit the detected beats to the first 10 seconds or so that would be okay for me.
 following 2 screenshots after 15 minutes
![1_](https://user-images.githubusercontent.com/12235843/51135249-d1964700-1839-11e9-9a65-2ac202214cc3.png)
![2_](https://user-images.githubusercontent.com/12235843/51135250-d22edd80-1839-11e9-9e10-36cfe62a6231.png)

**Comment by qlyoung** [comment]
A spectral flux is a value that indicates how much the sound energy in the current audio frame has deviated from the previous frame. So this function computes a time series of that. Later steps use that time series to look for regions in the series where a particularly large deviation occurs; this indicates that a beat has occurred (for example, the sound energy might noticeably spike on a drum hit and we can then say that a beat occurred at that time).

If you only need to detect beats in the first 10 seconds then yes you should be perfectly fine cutting down the number of frames you feed. Although it definitely seems like there is a bug somewhere. If you cut it down to 10 seconds and it's still taking forever I will try to look into it more when I have time this week.

**Comment by Tobias-De** [comment]
If i limit it to 500 it needs about 5 seconds per song. Thats okay for me. 
The accuracy is not as good as i have hoped but i can tweak it i think.
Thanks for your help 👍
